[package]
name = "cube"
version = "0.1.0"
authors = ["nabice <nabice@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.30"
nalgebra = "0.25"
arr_macro = "*"
multiarray = "*"
rand = "*"